/* 부모의 형질을 모두 가지는 대장균 찾기 */

SELECT 
	B.ID
	, B.GENOTYPE
	, A.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS A    /* 부모 */
JOIN ECOLI_DATA AS B    /* 자식 */
    ON A.ID = B.PARENT_ID
WHERE (A.GENOTYPE & B.GENOTYPE) = A.GENOTYPE
ORDER BY B.ID;