/* 카테고리 별 도서 판매량 집계하기 */

SELECT 
    CATEGORY
    , SUM(SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS S
    ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY;
