/* 저자 별 카테고리 별 매출액 집계하기 */

SELECT 
    A.AUTHOR_ID
    , A.AUTHOR_NAME
    , B.CATEGORY
    , SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS BS
    ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;