/* 입양 시각 구하기(2) */

WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR	-- 시작값
    UNION ALL
    SELECT HOUR + 1		-- 다음 숫자
    FROM HOURS
    WHERE HOUR < 23		-- 조건을 걸어서 0~23까지 생성
)

SELECT
    H.HOUR AS HOUR
    , COUNT(A.DATETIME) AS COUNT
FROM HOURS AS H
LEFT JOIN ANIMAL_OUTS AS A
    ON HOUR(A.DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR;