/* 년, 월, 성별 별 상품 구매 회원 수 구하기 */

SELECT 
    YEAR(SALES_DATE) AS YEAR
    , MONTH(SALES_DATE) AS MONTH
    , GENDER
    , COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O
    ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;