/* 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기 */

SELECT DISTINCT
    C.CAR_ID
    , C.CAR_TYPE
    , ROUND((C.DAILY_FEE * (1 - (0.01 * DP.DISCOUNT_RATE))) * 30 , 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON C.CAR_TYPE = DP.CAR_TYPE
WHERE C.CAR_TYPE IN ('SUV', '세단')
    AND DP.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (
        SELECT RH.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
        WHERE RH.START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
    )
GROUP BY CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;