/* 자동차 대여 기록 별 대여 금액 구하기 */

SELECT
    RH.HISTORY_ID
    , ROUND(C.DAILY_FEE * (1 - IFNULL(MAX(DP.DISCOUNT_RATE) / 100, 0)) * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1), 0) 
    AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON RH.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON C.CAR_TYPE = DP.CAR_TYPE
    AND (
        (DP.DURATION_TYPE = '90일 이상' AND DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 90) OR
        (DP.DURATION_TYPE = '30일 이상' AND DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 30) OR
        (DP.DURATION_TYPE = '7일 이상' AND DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 7)
    )
WHERE C.CAR_TYPE = '트럭'
GROUP BY RH.HISTORY_ID, C.DAILY_FEE, RH.START_DATE, RH.END_DATE
ORDER BY FEE DESC, RH.HISTORY_ID DESC;