/* 상품을 구매한 회원 비율 구하기 */

WITH JOIN_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT
    YEAR(O.SALES_DATE) AS YEAR
    , MONTH(O.SALES_DATE) AS MONTH
    , COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS
    , ROUND(
        COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM JOIN_2021)
        , 1
    ) AS PUCHASED_RATIO
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O
    ON U.USER_ID = O.USER_ID
WHERE O.USER_ID IN (SELECT USER_ID FROM JOIN_2021)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;